### ISSUE TITLE
Refactor all tests to use Bulloak

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-periphery#265] opened 2024-01-23 11:28 UTC
See:

- https://github.com/alexfertel/bulloak
- https://prberg.com/presentations/solidity-summit-2023

**Comment by smol-ninja** [comment] 2024-01-24 19:46
Should it be a part of V2.2?

**Comment by PaulRBerg** [comment] 2024-01-24 20:11
Nope, it shouldn't

**Comment by smol-ninja** [comment] 2024-07-30 22:36
Duplicate of https://github.com/sablier-labs/v2-core/issues/799

**Closed by smol-ninja** 2024-07-30 22:36 UTC
Labels: effort: epic, type: test, priority: 2, work: complicated
